[project]
name = "project-noah"
version = "0.1.0"
dependencies = [
    "fastapi[all]",
    "sqlalchemy == 2",
    "graphene-sqlalchemy",
    "psycopg2",
    "supabase"
]

[project.scripts]
project-noah = "project_noah:main"

[tool.setuptools]
py-modules = []
packages = ["project_noah"]
