// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Campaign struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type Mutation struct {
}

type NewCampaign struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewUser struct {
	SupabaseID       string `json:"supabaseId"`
	Email            string `json:"email"`
	MarketingConsent bool   `json:"marketingConsent"`
}

type Query struct {
}

type User struct {
	ID               string `json:"id"`
	SupabaseID       string `json:"supabaseId"`
	Email            string `json:"email"`
	MarketingConsent bool   `json:"marketingConsent"`
}
